// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {CircomVerifier} from "../src/CircomVerifier.sol";
import {IVerifier, EvidenceVerdict} from "../src/IVerifier.sol";
import {GalacticTrust} from "../src/GalacticTrust.sol";

/// @dev The real proof system behind the tri-state gate.
///
/// These run against genuine Groth16 proofs generated by `circuit/genproofs.js`. Nothing
/// here mocks the pairing: a `MockVerifier` proves that GLT reacts to a verdict, which is
/// already covered in GalacticTrust.t.sol. What only these tests can show is that the
/// circuit constrains what it claims to.
///
/// Per the SESSION.md §5 lesson about vacuous properties, every assertion here has been
/// checked by breaking the thing it describes and confirming it goes red — see the
/// comments marked "VACUITY CHECK".
contract CircomVerifierTest is Test {
    CircomVerifier internal verifier;

    address internal owner = address(this);
    address internal submitter = makeAddr("submitter");
    address internal attester1 = makeAddr("attester1");
    address internal attester2 = makeAddr("attester2");
    address internal attester3 = makeAddr("attester3");
    address internal curator1 = makeAddr("curator1");
    address internal curator2 = makeAddr("curator2");
    address internal outsider = makeAddr("outsider");

    GalacticTrust internal glt;

    uint256 internal constant MIN_STAKE = 1_000e18;
    uint256 internal constant TREASURY = 1_000_000e18;
    uint256 internal constant BOND = 5_000e18;
    uint256 internal constant REWARD = 100e18;
    uint256 internal constant CHALLENGE_BOND = 100e18;
    uint256 internal constant CURATOR_BOND = 1_000e18;

    /// @dev Matches the content hashes in test/fixtures/proofs.json. Tier 3 = R2.
    bytes32 internal constant CONFIRMED_HASH = 0x1111111111111111111111111111111111111111111111111111111111111111;
    bytes32 internal constant REFUTED_HASH = 0x2222222222222222222222222222222222222222222222222222222222222222;
    uint8 internal constant TIER_R2 = 3;

    struct Fixture {
        uint256 deviceKeyHash;
        uint8 tier;
        uint256 reading;
        bytes32 contentHash;
        uint256[4] publicSignals;
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
    }

    Fixture internal confirmed;
    Fixture internal refuted;
    Fixture internal refutedTier0;
    Fixture internal unapproved;

    function setUp() public {
        string memory json = vm.readFile("test/fixtures/proofs.json");
        confirmed = _load(json, ".confirmed");
        refuted = _load(json, ".refuted");
        refutedTier0 = _load(json, ".refutedTier0");
        unapproved = _load(json, ".unapproved");

        verifier = new CircomVerifier(owner);
        verifier.approveDevice(confirmed.deviceKeyHash);

        // The constants above are documentation, not the value under test. Assert the
        // fixtures actually carry them, so editing one side cannot quietly diverge.
        assertEq(confirmed.contentHash, CONFIRMED_HASH, "confirmed fixture hash drifted");
        assertEq(refuted.contentHash, REFUTED_HASH, "refuted fixture hash drifted");
        assertEq(confirmed.tier, TIER_R2, "confirmed fixture tier drifted");
        // The hash the test submits must be the one the proof commits to. Checking the
        // fixture against a local constant is not enough — the fixture could be internally
        // consistent and still disagree with the proof.
        assertEq(
            confirmed.publicSignals[0],
            uint256(confirmed.contentHash),
            "fixture hash must equal publicSignals[0] or the proof cannot verify"
        );
        assertEq(
            refuted.publicSignals[0],
            uint256(refuted.contentHash),
            "refuted: fixture hash must equal publicSignals[0]"
        );
        assertEq(
            uint8(confirmed.publicSignals[2]), 1, "confirmed fixture must carry verdict 1"
        );
        assertEq(uint8(refuted.publicSignals[2]), 0, "refuted fixture must carry verdict 0");
        assertTrue(
            confirmed.deviceKeyHash != unapproved.deviceKeyHash, "the two device fixtures must differ"
        );
        assertTrue(
            confirmed.contentHash == unapproved.contentHash,
            "the unapproved fixture is meant to target the same evidence"
        );
    }

    function _load(string memory json, string memory key) internal pure returns (Fixture memory) {
        string memory obj = key;
        Fixture memory f;
        f.deviceKeyHash = vm.parseJsonUint(json, string.concat(obj, ".deviceKeyHash"));
        f.tier = uint8(vm.parseJsonUint(json, string.concat(obj, ".tier")));
        f.reading = vm.parseJsonUint(json, string.concat(obj, ".reading"));
        // Read the content hash from the fixture rather than from a constant in this file.
        // The constants below are only cross-checks; deriving the value under test from a
        // second copy of it is how a fixture starts lying without anyone noticing.
        // The fixture stores contentHash as a decimal string; cast rather than parse, because
        // `vm.parseJsonString` on a bare hex string coerces it as a JSON number and
        // `vm.parseBytes32` then reinterprets the digits — yielding a different bytes32
        // than the proof commits to, with no error anywhere.
        f.contentHash = bytes32(vm.parseJsonUint(json, string.concat(obj, ".contentHash")));
        f.publicSignals[0] = vm.parseJsonUint(json, string.concat(obj, ".publicSignals[0]"));
        f.publicSignals[1] = vm.parseJsonUint(json, string.concat(obj, ".publicSignals[1]"));
        f.publicSignals[2] = vm.parseJsonUint(json, string.concat(obj, ".publicSignals[2]"));
        f.publicSignals[3] = vm.parseJsonUint(json, string.concat(obj, ".publicSignals[3]"));
        f.a[0] = vm.parseJsonUint(json, string.concat(obj, ".proof.a[0]"));
        f.a[1] = vm.parseJsonUint(json, string.concat(obj, ".proof.a[1]"));
        f.b[0][0] = vm.parseJsonUint(json, string.concat(obj, ".proof.b[0][0]"));
        f.b[0][1] = vm.parseJsonUint(json, string.concat(obj, ".proof.b[0][1]"));
        f.b[1][0] = vm.parseJsonUint(json, string.concat(obj, ".proof.b[1][0]"));
        f.b[1][1] = vm.parseJsonUint(json, string.concat(obj, ".proof.b[1][1]"));
        f.c[0] = vm.parseJsonUint(json, string.concat(obj, ".proof.c[0]"));
        f.c[1] = vm.parseJsonUint(json, string.concat(obj, ".proof.c[1]"));
        return f;
    }

    function _submit(Fixture memory f, uint8 verdict) internal {
        verifier.submitProof(f.contentHash, f.tier, verdict, f.deviceKeyHash, f.a, f.b, f.c);
    }

    function _verdict(Fixture memory f) internal view returns (EvidenceVerdict) {
        return verifier.verifyEvidence(f.contentHash, f.tier);
    }

    // ---------- the three states ----------

    /// The base case. Nothing has been submitted, so nothing has been claimed, so the
    /// honest answer is UNRESOLVED — not CONFIRMED, which would be the contract inventing
    /// an opinion on the submitter's behalf.
    function test_AbsentProofIsUnresolved() public view {
        assertEq(
            uint8(_verdict(confirmed)),
            uint8(EvidenceVerdict.UNRESOLVED),
            "nothing submitted must not read as an opinion"
        );
        assertFalse(verifier.hasProof(CONFIRMED_HASH, TIER_R2), "no proof recorded");
    }

    /// A signed reading inside its tier's envelope.
    function test_InEnvelopeReadingIsConfirmed() public {
        _submit(confirmed, 1);
        assertEq(uint8(_verdict(confirmed)), uint8(EvidenceVerdict.CONFIRMED));
    }

    /// The same device signs a reading outside its tier's envelope. REFUTED here is a
    /// *proof that a signed reading breaks the rules*, not merely the absence of a
    /// friendly proof — that is the whole reason the verdict is constrained in-circuit.
    function test_OutOfEnvelopeReadingIsRefuted() public {
        _submit(refuted, 0);
        assertEq(uint8(_verdict(refuted)), uint8(EvidenceVerdict.REFUTED));
    }

    /// Same reading value, same signer, declared UNVERIFIED instead of R2. Tier 0's
    /// ceiling is 100 and the reading is 5000, so the claim is refuted at tier 0 and
    /// confirmed at tier 3. This is what stops an unverifiable claim from being relabelled
    /// into a permissive tier.
    function test_TierIsLoadBearingNotDecorative() public {
        // The decisive pair: the SAME reading, the SAME signer, the SAME evidence hash, one
        // declared R2 (tier 3, ceiling 10000) and one declared UNVERIFIED (tier 0, ceiling
        // 100). Reading 5000 clears the first and breaks the second, so if the tier were
        // decorative both fixtures would carry the same verdict.
        assertEq(refutedTier0.reading, confirmed.reading, "the two must share a reading");
        assertEq(refutedTier0.contentHash, confirmed.contentHash, "the two must target one attestation");
        assertEq(refutedTier0.deviceKeyHash, confirmed.deviceKeyHash, "the two must share a signer");
        assertEq(refutedTier0.tier, 0, "the narrow fixture must be tier 0");
        assertEq(confirmed.tier, TIER_R2, "the wide fixture must be tier 3");

        // Different evidence hashes, so first-write-wins does not block the second.
        _submit(refutedTier0, 0);
        _submit(confirmed, 1);

        assertEq(
            uint8(_verdict(refutedTier0)),
            uint8(EvidenceVerdict.REFUTED),
            "5000 is out of spec for UNVERIFIED"
        );
        assertEq(
            uint8(_verdict(confirmed)),
            uint8(EvidenceVerdict.CONFIRMED),
            "5000 is in spec for R2"
        );
    }

    // ---------- the device registry is the trust boundary ----------

    /// VACUITY CHECK: with this assertion deleted, an unapproved device could submit a
    /// valid REFUTED for anyone else's evidence and permanently block their finalization.
    /// Reverting the registry check to `true` makes this test fail.
    function test_UnapprovedDeviceCannotSubmitAProof() public {
        assertFalse(verifier.approvedDevice(unapproved.deviceKeyHash), "device B must not start approved");
        vm.expectRevert(
            abi.encodeWithSelector(CircomVerifier.DeviceNotApproved.selector, unapproved.deviceKeyHash)
        );
        _submit(unapproved, 1);
        assertFalse(verifier.hasProof(CONFIRMED_HASH, TIER_R2), "nothing recorded");
    }

    /// The proof is bound to the key that signed. Fixture `unapproved` is a fully valid
    /// proof — the circuit is satisfied by it — and only the registry stops it. That
    /// distinction is the point: the circuit proves a signature, the registry decides
    /// whose signature counts.
    function test_SameProofAcceptedOnceItsDeviceIsApproved() public {
        // Submitting device B's proof under its own key hash while device A holds the only
        // approval is refused. Approve B, and the byte-identical proof is accepted. That
        // the rejection was about the device and not the proof is the point: the circuit
        // was satisfied by this proof all along.
        verifier.approveDevice(unapproved.deviceKeyHash);
        _submit(unapproved, 1);
        assertTrue(verifier.hasProof(confirmed.contentHash, TIER_R2));
        assertEq(
            uint8(_verdict(confirmed)), uint8(EvidenceVerdict.CONFIRMED), "B's proof confirms the evidence"
        );
    }

    function test_OwnerCannotApproveWithoutBeingOwner() public {
        vm.prank(outsider);
        vm.expectRevert();
        verifier.approveDevice(unapproved.deviceKeyHash);
    }

    function test_RevokedDeviceLosesTheAbilityToSubmitNewProofs() public {
        verifier.revokeDevice(confirmed.deviceKeyHash);
        assertFalse(verifier.approvedDevice(confirmed.deviceKeyHash));
        vm.expectRevert(
            abi.encodeWithSelector(CircomVerifier.DeviceNotApproved.selector, confirmed.deviceKeyHash)
        );
        _submit(refuted, 0);
    }

    /// A revoked device's already-recorded verdict stands. Revocation governs future
    /// claims; it is not a retroactive erasure, because a verdict that could be un-done
    /// after the fact is not a record.
    function test_RevocationDoesNotRetroactivelyEraseARecordedVerdict() public {
        _submit(refuted, 0);
        verifier.revokeDevice(confirmed.deviceKeyHash);
        assertEq(uint8(_verdict(refuted)), uint8(EvidenceVerdict.REFUTED));
    }

    // ---------- proof integrity ----------

    /// VACUITY CHECK: the caller supplies `verdict` as a calldata argument, so without the
    /// circuit constraining it to the envelope check a prover could submit an in-envelope
    /// proof labelled REFUTED. Removing `verdict === inEnvelope.out` from the circuit
    /// makes this fail.
    function test_CannotRelabelAProofAsRefutedWhenItIsInEnvelope() public {
        // `confirmed` genuinely clears the envelope, but we claim REFUTED.
        vm.expectRevert(bytes("proof rejected"));
        _submit(confirmed, 0);
        assertFalse(verifier.hasProof(CONFIRMED_HASH, TIER_R2), "a rejected proof records nothing");
    }

    /// The mirror image: an out-of-envelope proof cannot be dressed up as CONFIRMED.
    function test_CannotRelabelAnOutOfEnvelopeProofAsConfirmed() public {
        vm.expectRevert(bytes("proof rejected"));
        _submit(refuted, 1);
    }

    /// A proof is bound to the evidence hash it was made for. Replaying it against a
    /// different attestation must fail even though the signature is genuine.
    function test_ProofCannotBeReplayedOntoAnotherEvidenceHash() public {
        // Must be a hash inside the BN254 field, or this reverts on NotInField before the pairing
        // is reached and the test quietly stops testing what it claims to. The field prime
        // begins 0x30, so the leading byte has to be below 0x30 — 0x3333... is not, and a
        // random keccak256 usually is not either.
        bytes32 other = 0x2222222222222222222222222222222222222222222222222222222222222223;
        assertTrue(other != confirmed.contentHash, "the replay target must differ from the source");
        assertLt(uint256(other), 21888242871839275222246405745257275088548364400416034343698204186575808495617);
        vm.expectRevert(bytes("proof rejected"));
        verifier.submitProof(other, TIER_R2, 1, confirmed.deviceKeyHash, confirmed.a, confirmed.b, confirmed.c);
    }

    /// Nor onto another tier. The tier is a public signal, so changing it invalidates the
    /// pairing — this is what makes tier relabelling detectable at all.
    function test_ProofCannotBeReplayedAtAnotherTier() public {
        vm.expectRevert(bytes("proof rejected"));
        verifier.submitProof(
            CONFIRMED_HASH, uint8(TIER_R2 + 1), 1, confirmed.deviceKeyHash, confirmed.a, confirmed.b, confirmed.c
        );
    }

    /// Claiming an approved deviceKeyHash while signing with a key of your own is the
    /// attack that `deviceKeyHash === Poseidon(Ax, Ay)` in the circuit exists to stop.
    /// VACUITY CHECK: delete that constraint, regenerate the fixtures, and this goes green
    /// on `unapproved`'s proof — a complete bypass of the registry.
    function test_CannotClaimAnApprovedDeviceKeyWithoutItsPrivateKey() public {
        // Submit the unapproved device's genuine proof while asserting device A's hash.
        vm.expectRevert(bytes("proof rejected"));
        verifier.submitProof(
            CONFIRMED_HASH, TIER_R2, 1, confirmed.deviceKeyHash, unapproved.a, unapproved.b, unapproved.c
        );
    }

    function test_GarbageProofIsRejected() public {
        uint256[2] memory a;
        uint256[2][2] memory b;
        uint256[2] memory c;
        a[0] = 1;
        a[1] = 2;
        c[0] = 3;
        c[1] = 4;
        b[0][0] = 5;
        b[0][1] = 6;
        b[1][0] = 7;
        b[1][1] = 8;
        vm.expectRevert(bytes("proof rejected"));
        verifier.submitProof(CONFIRMED_HASH, TIER_R2, 1, confirmed.deviceKeyHash, a, b, c);
        assertEq(
            uint8(_verdict(confirmed)),
            uint8(EvidenceVerdict.UNRESOLVED),
            "garbage must leave the claim unresolved, not answered"
        );
    }

    function test_RevertWhen_TierOutOfRange() public {
        vm.expectRevert(abi.encodeWithSelector(CircomVerifier.TierOutOfRange.selector, uint8(7)));
        verifier.submitProof(CONFIRMED_HASH, 7, 1, confirmed.deviceKeyHash, confirmed.a, confirmed.b, confirmed.c);
    }

    function test_RevertWhen_VerdictOutOfRange() public {
        vm.expectRevert(abi.encodeWithSelector(CircomVerifier.InvalidVerdict.selector, uint8(2)));
        verifier.submitProof(CONFIRMED_HASH, TIER_R2, 2, confirmed.deviceKeyHash, confirmed.a, confirmed.b, confirmed.c);
    }

    /// A bytes32 at or above the BN254 field prime does not round-trip: `hash` and
    /// `hash - SNARK_FIELD` would encode to the same field element, so two distinct pieces
    /// of evidence would share a verdict.
    function test_RevertWhen_EvidenceHashNotInField() public {
        uint256 prime = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        vm.expectRevert(abi.encodeWithSelector(CircomVerifier.NotInField.selector, prime));
        verifier.submitProof(
            bytes32(prime), TIER_R2, 1, confirmed.deviceKeyHash, confirmed.a, confirmed.b, confirmed.c
        );
    }

    /// `hash - SNARK_FIELD` and `hash` encode to the same field element, so accepting
    /// out-of-field hashes would let one attestation read another's verdict. Refusing is
    /// the only safe answer; the cost is that most `keccak256` hashes become unprovable.
    function test_HashOutsideTheFieldIsRefusedNotReduced() public {
        uint256 prime = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        bytes32 above = bytes32(prime + 1);
        assertFalse(verifier.isProvable(above), "prime+1 must be refused");
        assertFalse(verifier.isProvable(bytes32(prime)), "the prime itself must be refused");

        // Both reduce to the same field element as 1 and 2. Neither may be provable.
        assertFalse(verifier.isProvable(bytes32(prime + 1)), "collision case 1");
        assertFalse(verifier.isProvable(bytes32(prime + 2)), "collision case 2");
        assertTrue(verifier.isProvable(bytes32(uint256(1))), "small hashes are fine");
    }

    /// A uniform bytes32 is above the field prime most of the time, because the field is 254
    /// bits and a bytes32 is 256. That is a large fraction of real hashes, so the failure
    /// mode has to be visible rather than a silent revert loop — and the number quoted in
    /// the docs has to be checked rather than believed.
    function test_MostRandomHashesAreUnprovable() public pure {
        uint256 prime = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

        // 2^254 is the first 2^254 out-of-range value; the whole top half of the byte
        // space is out of field, since the prime is just under 2^254.
        assertLt(prime, 1 << 254, "the BN254 prime is below 2^254");

        // Count the out-of-field band [prime, 2^256). The `+ 1` wraps in checked arithmetic
        // when the difference is exactly 2^256-1, so it goes in `unchecked` — the band is
        // legitimately that wide.
        uint256 outOfField;
        unchecked {
            outOfField = (type(uint256).max - prime) + 1;
        }
        // permille = outOfField * 1000 / 2^256. Multiplying outOfField by 1000 overflows, so
        // drop the low 248 bits first — they cannot affect a three-digit result — then
        // divide by 256 to restore the scale.
        uint256 permille;
        unchecked {
            permille = ((outOfField >> 248) * 1000) / 256;
        }
        assertGt(permille, 500, "more than half of all bytes32 values are out of field");
        assertLt(permille, 1000, "sanity: not all of them");
    }

    /// First write wins, so a verdict cannot be flipped around a finalization.
    function test_RevertWhen_ProofAlreadySubmitted() public {
        _submit(refuted, 0);
        vm.expectRevert(
            abi.encodeWithSelector(CircomVerifier.ProofAlreadySubmitted.selector, REFUTED_HASH, TIER_R2)
        );
        _submit(refuted, 0);
        assertEq(uint8(_verdict(refuted)), uint8(EvidenceVerdict.REFUTED), "verdict unchanged");
    }

    // ---------- integration with GLT ----------

    /// @dev A real REFUTED blocks finalization and routes the attestation to the panel,
    /// which is the whole point of the gate. Solvency is asserted because a green test
    /// suite here means nothing if the escrow bookkeeping moved.
    function test_RealRefutationBlocksFinalizationAndRoutesToPanel() public {
        _setUpGlt();
        vm.prank(owner);
        glt.setVerifier(address(verifier));

        _submit(refuted, 0);

        bytes32 id = _gltSubmit(REFUTED_HASH);
        _signTwo(id);
        _skipWindow();

        vm.expectRevert(
            abi.encodeWithSelector(
                GalacticTrust.EvidenceNotFinalizable.selector, id, uint8(EvidenceVerdict.REFUTED)
            )
        );
        glt.finalizeAttestation(id);

        uint256 supplyBefore = glt.totalSupply();
        _gltRejectReferral(id);
        glt.finalizeAttestation(id);
        assertEq(glt.totalSupply(), supplyBefore + REWARD, "mints only after a human ruling");
        _gltAssertSolvent();
    }

    /// With no proof submitted the verifier says UNRESOLVED, and an UNRESOLVED claim goes
    /// to the panel rather than minting. Absence of a proof is not a clean bill of health.
    function test_UnresolvedFromNoProofAlsoRoutesToPanel() public {
        _setUpGlt();
        vm.prank(owner);
        glt.setVerifier(address(verifier));

        bytes32 id = _gltSubmit(REFUTED_HASH);
        _signTwo(id);
        _skipWindow();

        assertEq(uint8(glt.evidenceVerdict(id)), uint8(EvidenceVerdict.UNRESOLVED));
        vm.expectRevert(
            abi.encodeWithSelector(
                GalacticTrust.EvidenceNotFinalizable.selector, id, uint8(EvidenceVerdict.UNRESOLVED)
            )
        );
        glt.finalizeAttestation(id);
        _gltAssertSolvent();
    }

    /// A genuine CONFIRMED finalizes on the normal quorum path.
    function test_RealConfirmationFinalizesNormally() public {
        _setUpGlt();
        vm.prank(owner);
        glt.setVerifier(address(verifier));

        _submit(confirmed, 1);

        bytes32 id = _gltSubmit(CONFIRMED_HASH);
        _signTwo(id);
        _skipWindow();
        glt.finalizeAttestation(id);

        assertEq(uint8(glt.getAttestation(id).status), uint8(GalacticTrust.AttestationStatus.FINALIZED));
        _gltAssertSolvent();
    }

    /// The tier GLT declares is the tier the proof must match, and GLT's R2 is index 3.
    /// If these ever disagree the whole gate silently reads UNRESOLVED forever.
    function test_GltTierIndexMatchesTheCircuitEnvelope() public pure {
        assertEq(uint8(GalacticTrust.EvidenceTier.UNVERIFIED), 0);
        assertEq(uint8(GalacticTrust.EvidenceTier.R2), TIER_R2);
    }

    // ---------- GLT helpers ----------

    function _setUpGlt() internal {
        glt = new GalacticTrust(owner, MIN_STAKE, address(0), TREASURY, submitter);
        glt.registerAttester(attester1, 100);
        glt.registerAttester(attester2, 100);
        glt.registerAttester(attester3, 100);
        glt.registerCurator(curator1, 100);
        glt.registerCurator(curator2, 100);

        vm.startPrank(owner);
        glt.setRewardAmount(REWARD);
        glt.setAttesterBondAmount(BOND);
        glt.setChallengeBondAmount(CHALLENGE_BOND);
        glt.setCuratorBondAmount(CURATOR_BOND);
        vm.stopPrank();

        _gltFund(attester1);
        _gltFund(attester2);
        _gltFund(attester3);
        _gltFundCurator(curator1);
        _gltFundCurator(curator2);
    }

    function _gltFund(address who) internal {
        vm.prank(submitter);
        glt.transfer(who, BOND * 2);
        vm.prank(who);
        glt.fundAttesterBond(BOND);
    }

    function _gltFundCurator(address who) internal {
        vm.prank(submitter);
        glt.transfer(who, CURATOR_BOND * 2);
        vm.prank(who);
        glt.fundCuratorBond(CURATOR_BOND);
    }

    function _gltAssertSolvent() internal {
        assertGe(glt.balanceOf(address(glt)), glt.totalLiabilities(), "contract owes more than it holds");
    }

    /// @dev GLT derives the attestation id from (submitter, contentHash, timestamp, secret),
    /// and Foundry does not advance `block.timestamp` between calls, so a repeated
    /// contentHash needs a distinct secret or the second submission overwrites the first.
    uint256 internal secretNonce;

    function _gltSubmit(bytes32 contentHash) internal returns (bytes32 id) {
        vm.prank(submitter);
        id = glt.submitAttestation(
            contentHash, keccak256(abi.encode("secret", secretNonce++)), GalacticTrust.EvidenceTier.R2
        );
    }

    function _signTwo(bytes32 id) internal {
        vm.prank(attester1);
        glt.signAttestation(id);
        vm.prank(attester2);
        glt.signAttestation(id);
    }

    function _skipWindow() internal {
        vm.warp(block.timestamp + glt.CHALLENGE_WINDOW() + 1);
    }

    function _gltRejectReferral(bytes32 id) internal {
        _skipWindow();
        vm.prank(curator1);
        glt.castCuratorVote(id, false);
        vm.prank(curator2);
        glt.castCuratorVote(id, false);
        glt.tallyDispute(id);
    }
}